# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogs/exception_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog
from views import resources as resources_rc


class ExceptionDialog(QDialog):
    def __init__(self, *args, **kwargs):
        super(ExceptionDialog, self).__init__(*args, **kwargs)
        self.setFixedSize(578, 220)
        self.lblImg = QtWidgets.QLabel(self)
        self.lblImg.setGeometry(QtCore.QRect(10, 50, 111, 111))
        self.lblImg.setText("")
        self.lblImg.setPixmap(QtGui.QPixmap(":/imgs/resources/warning.png"))
        self.lblImg.setScaledContents(True)
        self.lblImg.setObjectName("lblImg")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(130, 76, 391, 41))
        self.label.setText("ERROR BLA BLA")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.setWindowTitle("ERROR!")

    def set_error_msg(self, msg):
        self.label.setText(msg)
